//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Depo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int ID { get; set; }
        public int IdWork { get; set; }
        public int IdVan { get; set; }
        public System.DateTime Date { get; set; }
        public bool Status { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Van Van { get; set; }
        public virtual Work Work { get; set; }
    }
}
